# Generated by Django 3.2.16 on 2023-01-23 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus_Stop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_group', models.TextField(default='', null=True)),
                ('bus_name', models.TextField(default='', null=True)),
                ('latitude', models.FloatField(default=True)),
                ('longitude', models.FloatField(default=True)),
                ('start_or_end', models.TextField(default='', null=True)),
                ('first', models.TextField(default='0')),
                ('service', models.TextField(default='0')),
            ],
            options={
                'db_table': 'bus_stop',
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.TextField()),
                ('s_latitude', models.FloatField(default=True)),
                ('s_longitude', models.FloatField(default=True)),
                ('e_latitude', models.FloatField(default=True)),
                ('e_longitude', models.FloatField(default=True)),
                ('sigungucode', models.TextField(default='', null=True)),
                ('bus_group', models.TextField(default='', null=True)),
                ('s_busid', models.TextField(default='', null=True)),
                ('e_busid', models.TextField(default='', null=True)),
                ('service', models.TextField(default='0')),
                ('boarding_time', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User_Stop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.TextField()),
                ('start_bus_id', models.TextField(default='', null=True)),
                ('end_bus_id', models.TextField(default='', null=True)),
                ('start_bus_name', models.TextField(default='', null=True)),
                ('end_bus_name', models.TextField(default='', null=True)),
                ('bus_group', models.TextField(default='', null=True)),
            ],
            options={
                'db_table': 'user_stop',
            },
        ),
    ]
