# Generated by Django 4.1.5 on 2023-01-04 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('b_no', models.AutoField(db_column='b_no', primary_key=True, serialize=False)),
                ('b_title', models.CharField(blank=True, db_column='b_title', max_length=255, null=True)),
                ('b_note', models.CharField(blank=True, db_column='b_note', max_length=4096, null=True)),
                ('b_writer', models.CharField(blank=True, db_column='b_writer', max_length=50, null=True)),
                ('parent_no', models.IntegerField(blank=True, db_column='parent_no', null=True)),
                ('b_count', models.IntegerField(blank=True, db_column='b_count', null=True)),
                ('b_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'board',
            },
        ),
    ]
